import {
  Notification, Alert, Toast,
  Icon,
  Badge,
  BreadCrumbs, Crumb,
  Button, ButtonGroup,
  DropdownButton, DropdownMenu, DropdownMenuItem, MenuItem, DropdownMenuHeader, MenuHeader,
  Datepicker,
  Tab, Tabs,
  Modal, ModalHeader, ModalContent, ModalFooter,
  SalesPath,
  Form, FormElement, Input, Textarea, Radio, RadioGroup, Checkbox, CheckboxGroup, Select, Option,
  Picklist, PicklistItem,
  DateInput, Lookup, FieldSet,
  Tree, TreeNode,
  Spinner,
  Container, Grid, Row, Col,
  Text,
  MediaObject,

  PageHeader,
  PageHeaderHeading,
  PageHeaderHeadingTitle,
  PageHeaderDetail,
  PageHeaderDetailItem,
  PageHeaderDetailBody,
  PageHeaderDetailLabel,

  Popover,
  PopoverHeader,
  PopoverBody,

  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHeaderColumn,
  TableRowColumn,
  TableRowColumnActions,

  Toggle,
  Pill,
  util,
} from 'react-lightning-design-system';

util.setAssetRoot('/images');

module.exports = {
  Notification,
  Alert,
  Toast,
  Icon,
  Badge,
  BreadCrumbs,
  Crumb,
  Button,
  ButtonGroup,
  DropdownButton,
  DropdownMenu,
  DropdownMenuItem,
  MenuItem,
  DropdownMenuHeader,
  MenuHeader,
  Datepicker,
  Tab,
  Tabs,
  Modal,
  ModalHeader,
  ModalContent,
  ModalFooter,
  SalesPath,
  Form,
  FormElement,
  Input,
  Textarea,
  Radio,
  RadioGroup,
  Checkbox,
  CheckboxGroup,
  Select,
  Option,
  Picklist,
  PicklistItem,
  DateInput,
  Lookup,
  FieldSet,
  Tree,
  TreeNode,
  Spinner,
  Container,
  Grid,
  Row,
  Col,
  Text,
  MediaObject,
  PageHeader,
  PageHeaderHeading,
  PageHeaderHeadingTitle,
  PageHeaderDetail,
  PageHeaderDetailItem,
  PageHeaderDetailBody,
  PageHeaderDetailLabel,
  Popover,
  PopoverHeader,
  PopoverBody,
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHeaderColumn,
  TableRowColumn,
  TableRowColumnActions,
  Toggle,
  Pill,
};
